package org.hkpc.dtd.component.postgres.dao;

import org.hkpc.dtd.component.postgres.model.AccountRoleRelation;
import org.hkpc.dtd.component.postgres.model.AccountRoleRelationKey;

import java.util.List;

public interface AccountRoleRelationMapper {

    List<AccountRoleRelation> selectAllByAccountId(Integer userAccountId);
    /**
     * All methods below are auto-generated by MybatisGenerator {@link org.hkpc.dtd.component.postgres.mybatis.generator.MybatisGenerator}
     * Better don't modify them, otherwise the generator will override the changes when re-generating the code. <br>
     * 中文注释：以下所有方法由MybatisGenerator自动生成  {@link org.hkpc.dtd.component.postgres.mybatis.generator.MybatisGenerator}
     * 最好不要修改它们，否则当重新生成代码时，生成器将覆盖这些更改。
     */
    int deleteByPrimaryKey(AccountRoleRelationKey key);

    int insert(AccountRoleRelation row);

    int insertSelective(AccountRoleRelation row);

    AccountRoleRelation selectByPrimaryKey(AccountRoleRelationKey key);

    int updateByPrimaryKeySelective(AccountRoleRelation row);

    int updateByPrimaryKey(AccountRoleRelation row);
}
