package org.hkpc.dtd.component.postgres.dao;

import org.hkpc.dtd.component.postgres.model.DbConfig;

public interface DbConfigMapper {

    String selectByKey(String key);

    /**
     * All methods below are auto-generated by MybatisGenerator {@link org.hkpc.dtd.component.postgres.mybatis.generator.MybatisGenerator}
     * Better don't modify them, otherwise the generator will override the changes when re-generating the code. You can copy then modify them<br>
     * 中文注释：以下所有方法由MybatisGenerator自动生成  {@link org.hkpc.dtd.component.postgres.mybatis.generator.MybatisGenerator}
     * 最好不要修改它们，否则当重新生成代码时，生成器将覆盖这些更改。 你可以复制然后修改它们.
     */
    int deleteByPrimaryKey(Integer id);

    int insert(DbConfig row);

    int insertSelective(DbConfig row);

    DbConfig selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(DbConfig row);

    int updateByPrimaryKey(DbConfig row);
}
