package org.hkpc.dtd.component.postgres.dao;

import org.hkpc.dtd.component.postgres.model.UserAccount;

public interface UserAccountMapper {


    UserAccount selectByUsername(String username);

    /**
     * All methods below are auto-generated by MybatisGenerator {@link org.hkpc.dtd.component.postgres.mybatis.generator.MybatisGenerator}
     * Better don't modify them, otherwise the generator will override the changes when re-generating the code. You can copy then modify them<br>
     * 中文注释：以下所有方法由MybatisGenerator自动生成  {@link org.hkpc.dtd.component.postgres.mybatis.generator.MybatisGenerator}
     * 最好不要修改它们，否则当重新生成代码时，生成器将覆盖这些更改。 你可以复制然后修改它们.
     */
    int deleteByPrimaryKey(Integer id);

    int insert(UserAccount row);

    int insertSelective(UserAccount row);

    UserAccount selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(UserAccount row);

    int updateByPrimaryKey(UserAccount row);
}
